### PR TITLE
Update 03.md

### PR DESCRIPTION
**Pull request by locks**

### CODE REVIEW

**Review by amyrlam — APPROVED** [review]
:+1: not sure if covered by `| 10min | The book shelf approach to documentation | Ricardo Mendes |`

**Comment by MelSumner** [comment]
I think this will come up in the all-hands F2F, but if you resolve the conflicts, I'll merge it! 👍

**Comment by acorncom** [comment]
@MelSumner merge conflicts resolved

**Comment by MelSumner** [comment]
Thank you @acorncom 💯

**Pull request merged**
